#!/bin/sh

echo "$(mender -show-artifact): $(basename "$0") was called!" >&2

# Abort mocked download progress bar
systemctl stop mender-progressbar-mock

psplash-write "Installing Artifact..."
usleep $(( 1000 * 100 ))
psplash-write "PROGRESS 80"

exit 0
