#!/bin/sh

echo "$(mender -show-artifact): $(basename "$0") was called!" >&2

systemctl unmask psplash
systemctl start psplash

psplash-write "Started downloading Artifact..."
psplash-write "PROGRESS 30"

exit 0
